name: Fetch CRM and store JSON

on:
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight
  workflow_dispatch:

jobs:
  convert:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      
      - name: Install dependencies
        run: cd converter && npm install
      
      - name: Fetch CRM data and convert to JSON
        env:
            NODE_ENV: production
            DYNAMICS_TENANT_ID: ${{ secrets.DYNAMICS_TENANT_ID }}
            DYNAMICS_CLIENT_ID: ${{ secrets.DYNAMICS_CLIENT_ID }}
            DYNAMICS_CLIENT_SECRET: ${{ secrets.DYNAMICS_CLIENT_SECRET }}
            DYNAMICS_API_VERSION: 9.2
            DYNAMICS_ORG_URL: https://amigosls.api.crm.dynamics.com
        run: cd converter && npm run crm
      
      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add docs/crm
          git diff --quiet && git diff --staged --quiet || (git commit -am "chore: update converted JSON files" && git push origin HEAD:${{ github.ref_name }})
